# define some constants used across modules.

# common tag names
TAG_PUBLISHER = 'publisher'
TAG_IMAGES = 'images'

#doc tags
DOCTAG_URL = 'url'

# feed tags
FEEDTAG_TYPE = 'type'
FEEDTAG_NEXTPOLLTIME = 'nextPollTime'
FEEDTAG_POLLFREQUENCY = 'pollFrequency'
FEEDTAG_LASTPOLLTIME = 'lastPollTime'
FEEDTAG_URL = 'feedUrl'
FEEDTAG_LASTPUBDATE = 'lastPubDate'

# link tags
LINKTAG_ISPROCESSED = 'isProcessed'
LINKTAG_DOCKEY = 'docKey'
LINKTAG_SUMMARY = 'summary'
LINKTAG_SUMMARYTEXT = 'summaryText'
LINKTAG_SUMMARYIMAGES = 'summaryImages'
LINKTAG_PUBTIME = 'pubtime'
LINKTAG_TITLE = 'title'

# publisher tags
PUBLISHERTAG_TEXTSELECTOR = 'textSelector'
PUBLISHERTAG_IMAGESELECTORS = 'imageSelectors'

#job names
JOB_PROCESSFEED = 'processFeed'
JOBARG_PROCESSFEED_FEEDID = 'feedId'
JOB_PROCESSLINK = 'processLink'
JOBARG_PROCESSLINK_LINKID = 'linkId'
JOB_PARSEDOC = 'parseDoc'
JOBARG_PARSEDOC_DOCID = 'docId'
JOB_GETCANDIDATEDOCS = 'getCandidateDocs'
JOBARG_GETCANDIDATEDOCS_DOCID = 'docId'
JOB_COMPAREDOCS = 'compareDocs'
JOBARG_COMPAREDOCS_DOC1ID = 'doc1'
JOBARG_COMPAREDOCS_DOC2ID ='doc2'
JOB_CLUSTERDOCS = 'clusterDocs'
JOB_UPDATEDBTHROUGHPUT = 'updateDbThroughput'
JOB_UPDATEDBTHROUGHPUT_CONNECTIONSTRING = 'connectionString'
JOB_UPDATEDBTHROUGHPUT_READTHOUGHPUT = 'readThroughput'
JOB_UPDATEDBTHROUGHPUT_WRITETHOUGHPUT = 'writeThroughput'
JOB_UPDATEDBTHROUGHPUT_INDEXNAME = 'indexName'
JOB_CLEANUPDOCSHINGLES = 'cleanupDocShingles'
JOBARG_CLEANUPDOCSHINGLES_DOCID = 'docId'
JOB_CLEANUPDOCDISTANCES = 'cleanupDocDistances'
JOBARG_CLEANUPDOCDISTANCES_DOCID = 'docId'

#clustering job states
CLUSTER_STATE_INITIALIZED = 'initialized'
CLUSTER_STATE_NEW = 'new'
CLUSTER_STATE_STARTED = 'started'
CLUSTER_STATE_COMPLETED = 'completed'
